import { db } from './index.js'
import {
  alertRules,
  customers,
  forwarders,
  shipments,
  shipmentMilestones,
  shippingEmails,
  alerts,
  users,
  vendors,
  purchaseOrders,
  shipmentPos,
  shipmentHistory,
  emailAttachments,
} from './schema.js'

/**
 * Seed the database with default alert rules, sample customers,
 * forwarders, users, and a few example shipments for development.
 */
export async function seed() {
  console.log('Seeding database...')

  // ============================================
  // Users (PRD Personas)
  // ============================================
  const existingUsers = await db.select().from(users)
  if (existingUsers.length === 0) {
    await db.insert(users).values([
      {
        id: 'user-sunny',
        name: 'Sunny',
        email: 'sunny@cobalt.hk',
        role: 'COORDINATOR',
        avatarInitials: 'SC',
      },
      {
        id: 'user-amon',
        name: 'Amon',
        email: 'amon@cobalt.hk',
        role: 'MANAGER',
        avatarInitials: 'AM',
      },
      {
        id: 'user-amon-it',
        name: 'Amon (IT)',
        email: 'amon.it@cobalt.hk',
        role: 'ADMIN',
        avatarInitials: 'AI',
      },
    ])
    console.log('  Seeded 3 users')
  }

  // ============================================
  // Default Alert Rules (A1-A6)
  // ============================================
  const existingRules = await db.select().from(alertRules)
  if (existingRules.length === 0) {
    await db.insert(alertRules).values([
      {
        id: 'A1',
        name: 'No SO Received',
        description: 'Booking sent but no Shipping Order received from forwarder',
        state: 'BOOKED',
        triggerType: 'days_after',
        triggerReference: 'booking',
        thresholdDays: 2,
        severity: 'WARNING',
        enabled: true,
        locked: false,
      },
      {
        id: 'A2',
        name: 'Cut-off Approaching',
        description: 'CFS cut-off deadline is approaching, no Draft B/L received',
        state: 'CONFIRMED',
        triggerType: 'days_before',
        triggerReference: 'cutoff',
        thresholdDays: 1,
        severity: 'WARNING',
        enabled: true,
        locked: false,
      },
      {
        id: 'A3',
        name: 'Cut-off Passed',
        description: 'CFS cut-off has passed without Draft B/L — cargo may have missed vessel',
        state: 'CONFIRMED',
        triggerType: 'days_after',
        triggerReference: 'cutoff',
        thresholdDays: 0,
        severity: 'CRITICAL',
        enabled: true,
        locked: true,
      },
      {
        id: 'A4',
        name: 'No Final B/L',
        description: 'Draft B/L received but no Final B/L — vessel may not have departed',
        state: 'AT_WAREHOUSE',
        triggerType: 'days_after',
        triggerReference: 'draft_bl',
        thresholdDays: 5,
        severity: 'WARNING',
        enabled: true,
        locked: false,
      },
      {
        id: 'A5',
        name: 'No Telex Release',
        description: 'Final B/L received but no Telex Release — check freight payment status',
        state: 'SAILED',
        triggerType: 'days_after',
        triggerReference: 'final_bl',
        thresholdDays: 7,
        severity: 'INFO',
        enabled: true,
        locked: false,
      },
      {
        id: 'A6',
        name: 'No Delivery Confirmation',
        description: 'ETA has passed but no delivery confirmation received',
        state: 'RELEASED',
        triggerType: 'days_after',
        triggerReference: 'eta',
        thresholdDays: 3,
        severity: 'INFO',
        enabled: true,
        locked: false,
      },
    ])
    console.log('  Seeded 6 alert rules')
  }

  // ============================================
  // Sample Customers
  // ============================================
  const existingCustomers = await db.select().from(customers)
  if (existingCustomers.length === 0) {
    await db.insert(customers).values([
      { id: 'cust-001', name: 'New Lobster UK', code: 'NLOB' },
      { id: 'cust-002', name: 'SKIM US West', code: 'SKIM' },
      { id: 'cust-003', name: 'Daniels DE', code: 'DANL' },
      { id: 'cust-004', name: 'Marine Layer US', code: 'MLYR' },
      { id: 'cust-005', name: 'Fenwick UK', code: 'FENW' },
      { id: 'cust-006', name: 'Woolworths AU', code: 'WOOL' },
    ])
    console.log('  Seeded 6 customers')
  }

  // ============================================
  // Sample Forwarders
  // ============================================
  const existingForwarders = await db.select().from(forwarders)
  if (existingForwarders.length === 0) {
    await db.insert(forwarders).values([
      { id: 'fwd-001', name: 'Torque/Shipair' },
      { id: 'fwd-002', name: 'GFS' },
      { id: 'fwd-003', name: 'JAS Forwarding' },
      { id: 'fwd-004', name: 'DSV' },
      { id: 'fwd-005', name: 'Logwin' },
      { id: 'fwd-006', name: 'COSCO Logistics' },
      { id: 'fwd-007', name: 'ABC Freight' },
    ])
    console.log('  Seeded 7 forwarders')
  }

  // ============================================
  // Sample Vendors / Factories
  // ============================================
  const existingVendors = await db.select().from(vendors)
  if (existingVendors.length === 0) {
    const now = new Date()
    await db.insert(vendors).values([
      {
        id: 'vnd-001',
        name: 'Shenzhen Yida Knitting Co.',
        code: 'YIDA',
        type: 'factory',
        location: 'Shenzhen, Guangdong',
        contactEmail: 'sales@yida-knit.cn',
        contactPhone: '+86 755 8888 1234',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'vnd-002',
        name: 'Dongguan Haowei Garments',
        code: 'HOWE',
        type: 'factory',
        location: 'Dongguan, Guangdong',
        contactEmail: 'export@haowei.com.cn',
        contactPhone: '+86 769 2222 5678',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'vnd-003',
        name: 'Wing Tai Textiles',
        code: 'WTXT',
        type: 'subcontractor',
        location: 'Zhuhai, Guangdong',
        contactEmail: 'ops@wingtai.hk',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'vnd-004',
        name: 'Pearl River Trading Co.',
        code: 'PRTC',
        type: 'agent',
        location: 'Hong Kong',
        contactEmail: 'info@prtco.hk',
        contactPhone: '+852 3456 7890',
        createdAt: now,
        updatedAt: now,
      },
    ])
    console.log('  Seeded 4 vendors')
  }

  // ============================================
  // Sample Shipments (matching PRD examples)
  // ============================================
  const existingShipments = await db.select().from(shipments)
  if (existingShipments.length === 0) {
    const now = new Date()
    const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000)
    const daysFromNow = (d: number) => new Date(now.getTime() + d * 86400000)

    await db.insert(shipments).values([
      {
        id: 'ship-001',
        poNumbers: JSON.stringify(['100-100209', '100-100210', '100-100215']),
        customerId: 'cust-001',
        vendorId: 'vnd-001',
        forwarderId: 'fwd-001',
        route: 'SZ→UK',
        status: 'CONFIRMED',
        riskLevel: 'AT_RISK',
        bookingNo: 'MAEU-742931847',
        soNumber: 'SO-NLOB-001',
        itemStyleNo: 'ST-AW26-001',
        consigneeName: 'New Lobster Ltd',
        consigneeAddress: '45 Market Street, London EC3R 8BU, UK',
        containerNo: 'MSKU-7281945',
        mblNumber: 'CMDUSZ2026138',
        crd: daysAgo(5),
        cfsCutoff: daysAgo(2),
        etd: daysFromNow(15),
        eta: daysFromNow(45),
        warehouseStartDate: daysAgo(2),
        warehouseEndDate: daysFromNow(1),
        hblNumber: 'SZTOR88412',
        vesselName: 'OOCL PIRAEUS',
        voyageNumber: '215E',
        warehouseAddress: 'Yantian CFS Terminal, Gate 3',
        quantityShipped: 120,
        quantityUnit: 'cartons',
      },
      {
        id: 'ship-002',
        poNumbers: JSON.stringify(['2238941', '2238942']),
        customerId: 'cust-002',
        vendorId: 'vnd-002',
        forwarderId: 'fwd-002',
        route: 'SZ→LA',
        status: 'AT_WAREHOUSE',
        riskLevel: 'ON_TRACK',
        bookingNo: 'OOLU-S6209384',
        soNumber: 'SO-SKIM-002',
        itemStyleNo: 'ST-SS26-402',
        consigneeName: 'SKIM Inc.',
        consigneeAddress: '8200 Wilshire Blvd, Los Angeles, CA 90048, USA',
        containerNo: 'TCLU-5938201',
        mblNumber: 'CMDUSZ2026205',
        crd: daysAgo(10),
        cfsCutoff: daysAgo(7),
        warehouseStartDate: daysAgo(7),
        warehouseEndDate: daysAgo(3),
        etd: daysFromNow(5),
        eta: daysFromNow(25),
        hblNumber: 'SZ2C54172564',
        vesselName: 'CMA CGM MARCO POLO',
        quantityShipped: 200,
        quantityUnit: 'cartons',
      },
      {
        id: 'ship-003',
        poNumbers: JSON.stringify(['6131180898', '6131180899']),
        customerId: 'cust-003',
        vendorId: 'vnd-001',
        forwarderId: 'fwd-005',
        route: 'HK→DE',
        status: 'SAILED',
        riskLevel: 'ON_TRACK',
        bookingNo: 'HLCU-BK8847210',
        soNumber: 'SO-DANL-003',
        itemStyleNo: 'ST-AW26-505',
        consigneeName: 'Daniels GmbH',
        consigneeAddress: 'Hafenstraße 12, 20457 Hamburg, Germany',
        containerNo: 'MSCU-4412830',
        mblNumber: 'MAEUHK2026109',
        crd: daysAgo(20),
        cfsCutoff: daysAgo(17),
        warehouseStartDate: daysAgo(17),
        warehouseEndDate: daysAgo(14),
        etd: daysAgo(3),
        eta: daysFromNow(30),
        inDcDate: daysFromNow(32),
        hblNumber: 'HKHBG34521',
        vesselName: 'MAERSK SELETAR',
        voyageNumber: '426W',
        actualDeparture: daysAgo(3),
        warehouseAddress: 'Hong Kong International Terminal, Berth 5',
        quantityShipped: 500,
        quantityUnit: 'pieces',
      },
      {
        id: 'ship-004',
        poNumbers: JSON.stringify(['22491', '22492']),
        customerId: 'cust-003',
        vendorId: 'vnd-003',
        forwarderId: 'fwd-003',
        route: 'SZ→DE',
        status: 'AT_WAREHOUSE',
        riskLevel: 'DELAYED',
        bookingNo: 'MSCU-615027A',
        soNumber: 'SO-DANL-004A',
        itemStyleNo: 'ST-SS26-710',
        consigneeName: 'Daniels GmbH',
        consigneeAddress: 'Hafenstraße 12, 20457 Hamburg, Germany',
        containerNo: null,
        mblNumber: null,
        crd: daysAgo(15),
        cfsCutoff: daysAgo(12),
        warehouseStartDate: daysAgo(12),
        warehouseEndDate: daysAgo(9),
        etd: null,
        eta: null,
        hblNumber: 'SZJAS98712',
        warehouseAddress: 'Shekou CFS Yard 4',
        quantityShipped: 360,
        quantityUnit: 'cartons',
      },
      {
        id: 'ship-005',
        poNumbers: JSON.stringify(['ML-2026-0045']),
        customerId: 'cust-004',
        vendorId: 'vnd-002',
        forwarderId: 'fwd-004',
        route: 'SZ→US',
        status: 'BOOKED',
        riskLevel: 'ON_TRACK',
        bookingNo: 'EGLV-1029385746',
        vesselName: 'COSCO SHIPPING ARIES',
        voyageNumber: '038W',
        soNumber: null,
        itemStyleNo: 'ST-SS26-M45',
        consigneeName: 'Marine Layer Inc.',
        consigneeAddress: '580 Howard St, San Francisco, CA 94105, USA',
        containerNo: null,
        mblNumber: null,
        crd: daysFromNow(5),
        etd: daysFromNow(15),
        eta: daysFromNow(40),
        quantityShipped: 85,
        quantityUnit: 'cartons',
      },
      {
        id: 'ship-006',
        poNumbers: JSON.stringify(['FEN-MS-118997']),
        customerId: 'cust-005',
        vendorId: 'vnd-004',
        forwarderId: 'fwd-001',
        route: 'SZ→UK',
        status: 'RELEASED',
        riskLevel: 'ON_TRACK',
        bookingNo: 'YMLU-4738201',
        soNumber: 'SO-FENW-006',
        itemStyleNo: 'ST-AW26-991',
        consigneeName: 'Fenwick & Co.',
        consigneeAddress: '18 King Street, Manchester M2 6AG, UK',
        containerNo: 'EISU-9032156',
        mblNumber: 'EISZUK2026008',
        crd: daysAgo(40),
        cfsCutoff: daysAgo(37),
        warehouseStartDate: daysAgo(37),
        warehouseEndDate: daysAgo(33),
        etd: daysAgo(30),
        eta: daysAgo(2),
        inDcDate: daysAgo(1),
        actualDeparture: daysAgo(30),
        actualArrival: daysAgo(2),
        hblNumber: 'SZTOR77234',
        vesselName: 'EVER GIVEN',
        voyageNumber: '112E',
        warehouseAddress: 'Yantian CFS Terminal, Gate 7',
        quantityShipped: 40,
        quantityUnit: 'cbm',
      },
      {
        // Woolworths AU — linked to email-012 (NEEDS_REVIEW SO) and email-015 (REVIEWED_CORRECTED booking)
        id: 'ship-007',
        poNumbers: JSON.stringify(['5501-HK-AU', 'WW-AU-8801']),
        customerId: 'cust-006',
        vendorId: 'vnd-001',
        forwarderId: 'fwd-006',
        route: 'HK→AU',
        status: 'BOOKED',
        riskLevel: 'ON_TRACK',
        bookingNo: 'COSU-3392018E',
        soNumber: null,
        itemStyleNo: null,
        consigneeName: 'Woolworths Group Ltd',
        consigneeAddress: '1 Woolworths Way, Bella Vista NSW 2153, Australia',
        containerNo: null,
        mblNumber: null,
        crd: daysFromNow(10),
        cfsCutoff: daysFromNow(3),
        etd: daysFromNow(5),
        eta: daysFromNow(25),
        hblNumber: null,
        vesselName: 'COSCO SHIPPING PISCES',
        voyageNumber: '055E',
        warehouseAddress: '葵涌货柜码头 CT8 仓库',
        quantityShipped: 200,
        quantityUnit: 'cartons',
      },
      {
        // Test Customer — linked to email-006 (NEEDS_REVIEW booking, low confidence)
        id: 'ship-008',
        poNumbers: JSON.stringify(['TEST-9999']),
        customerId: null, // New account, not fully set up
        vendorId: null,
        forwarderId: 'fwd-002',
        route: 'SZ→AU',
        status: 'BOOKED',
        riskLevel: 'ON_TRACK',
        bookingNo: null,
        soNumber: null,
        itemStyleNo: null,
        consigneeName: null,
        consigneeAddress: null,
        containerNo: null,
        mblNumber: null,
        crd: daysFromNow(15),
        cfsCutoff: daysFromNow(8),
        etd: daysFromNow(10),
        eta: daysFromNow(28),
        hblNumber: null,
        vesselName: 'MSC ANNA',
        voyageNumber: 'FD612',
        quantityShipped: null,
        quantityUnit: null,
      },
    ])
    console.log('  Seeded 8 shipments')

    // Milestones for the shipments
    await db.insert(shipmentMilestones).values([
      // Ship-001: New Lobster UK
      { id: 'ms-001', shipmentId: 'ship-001', milestoneType: 'BOOKING_SENT', occurredAt: daysAgo(12) },
      { id: 'ms-002', shipmentId: 'ship-001', milestoneType: 'SO_RECEIVED', occurredAt: daysAgo(10) },
      // Ship-002: SKIM
      { id: 'ms-003', shipmentId: 'ship-002', milestoneType: 'BOOKING_SENT', occurredAt: daysAgo(14) },
      { id: 'ms-004', shipmentId: 'ship-002', milestoneType: 'SO_RECEIVED', occurredAt: daysAgo(12) },
      { id: 'ms-005', shipmentId: 'ship-002', milestoneType: 'DRAFT_BL_RECEIVED', occurredAt: daysAgo(5) },
      // Ship-003: Daniels sailed
      { id: 'ms-006', shipmentId: 'ship-003', milestoneType: 'BOOKING_SENT', occurredAt: daysAgo(25) },
      { id: 'ms-007', shipmentId: 'ship-003', milestoneType: 'SO_RECEIVED', occurredAt: daysAgo(22) },
      { id: 'ms-008', shipmentId: 'ship-003', milestoneType: 'DRAFT_BL_RECEIVED', occurredAt: daysAgo(15) },
      { id: 'ms-009', shipmentId: 'ship-003', milestoneType: 'FINAL_BL_RECEIVED', occurredAt: daysAgo(5) },
      // Ship-004: Daniels delayed
      { id: 'ms-010', shipmentId: 'ship-004', milestoneType: 'BOOKING_SENT', occurredAt: daysAgo(18) },
      { id: 'ms-011', shipmentId: 'ship-004', milestoneType: 'SO_RECEIVED', occurredAt: daysAgo(16) },
      { id: 'ms-012', shipmentId: 'ship-004', milestoneType: 'DRAFT_BL_RECEIVED', occurredAt: daysAgo(10) },
      // Ship-005: Marine Layer booked
      { id: 'ms-013', shipmentId: 'ship-005', milestoneType: 'BOOKING_SENT', occurredAt: daysAgo(1) },
      // Ship-006: Fenwick released
      { id: 'ms-014', shipmentId: 'ship-006', milestoneType: 'BOOKING_SENT', occurredAt: daysAgo(45) },
      { id: 'ms-015', shipmentId: 'ship-006', milestoneType: 'SO_RECEIVED', occurredAt: daysAgo(42) },
      { id: 'ms-016', shipmentId: 'ship-006', milestoneType: 'DRAFT_BL_RECEIVED', occurredAt: daysAgo(35) },
      { id: 'ms-017', shipmentId: 'ship-006', milestoneType: 'FINAL_BL_RECEIVED', occurredAt: daysAgo(32) },
      { id: 'ms-018', shipmentId: 'ship-006', milestoneType: 'TELEX_RELEASED', occurredAt: daysAgo(5) },
      // Ship-007: Woolworths AU — just booked
      { id: 'ms-019', shipmentId: 'ship-007', milestoneType: 'BOOKING_SENT', occurredAt: daysAgo(3) },
      // Ship-008: Test Customer — just booked
      { id: 'ms-020', shipmentId: 'ship-008', milestoneType: 'BOOKING_SENT', occurredAt: daysAgo(1) },
    ])
    console.log('  Seeded 20 milestones')

    // Sample alerts
    await db.insert(alerts).values([
      {
        id: 'alert-001',
        shipmentId: 'ship-001',
        ruleId: 'A3',
        severity: 'CRITICAL',
        message: 'Cut-off passed — cargo may have missed the vessel',
        status: 'ACTIVE',
        triggeredAt: daysAgo(2),
      },
      {
        id: 'alert-002',
        shipmentId: 'ship-004',
        ruleId: 'A4',
        severity: 'WARNING',
        message: 'No Final B/L received 10 days after Draft B/L',
        status: 'ACTIVE',
        triggeredAt: daysAgo(5),
      },
      {
        id: 'alert-003',
        shipmentId: 'ship-002',
        ruleId: 'A4',
        severity: 'WARNING',
        message: 'Awaiting departure confirmation — Draft B/L received 5 days ago',
        status: 'ACTIVE',
        triggeredAt: daysAgo(0),
      },
    ])
    console.log('  Seeded 3 alerts')
  }

  // ============================================
  // Sample Emails (pre-processed inbox data)
  // ============================================
  const existingEmails = await db.select().from(shippingEmails)
  if (existingEmails.length === 0) {
    const now = new Date()
    const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000)

    await db.insert(shippingEmails).values([
      {
        id: 'email-001',
        messageId: '<so-ml2026-0045@dsv.com>',
        subject: 'RE: 入仓单 / Shipping Order - PO# ML-2026-0045 - SZ→US',
        sender: 'ops@dsv.com',
        receivedAt: daysAgo(1),
        bodyText: `Dear Cobalt Team,\n\nPlease find below the shipping order / 入仓单 for the following shipment:\n\nPO Number: ML-2026-0045\nCustomer: Marine Layer US\nRoute: SZ→US (Shenzhen → Los Angeles)\n\nCargo Details:\n- 85 cartons (箱) knitted garments\n- Gross Weight: 1,700 KG\n- Volume: 8.5 CBM\n\nWarehouse Details:\nAddress: Yantian International Container Terminal, Gate 3\nCFS Cut-off: 2026-04-20 17:00 (截仓时间)\n\nPlease deliver cargo to the above address before the cut-off deadline.\n\nVessel: COSCO SHIPPING ARIES\nVoyage: 038W\nETD: 2026-04-22\nETA: 2026-05-10\n\nIf you have any questions, please contact us.\n\nBest regards,\nDSV Shenzhen Operations\nops@dsv.com`,
        emailType: 'SHIPPING_ORDER',
        extractedData: JSON.stringify({
          po_numbers: ['ML-2026-0045'],
          customer: 'Marine Layer US',
          forwarder: 'DSV',
          route: 'SZ→US',
          booking_no: 'EGLV-1029385746',
          so_number: null,
          item_style_no: 'ST-SS26-M45',
          consignee_name: 'Marine Layer Inc.',
          consignee_address: '580 Howard St, San Francisco, CA 94105, USA',
          hbl_number: null,
          mbl_number: null,
          container_no: null,
          vessel: 'COSCO SHIPPING ARIES',
          voyage_number: '038W',
          etd: '2026-04-22',
          eta: '2026-05-10',
          crd: '2026-05-01',
          cfs_cutoff: '2026-04-20',
          warehouse_address: 'Yantian International Container Terminal, Gate 3',
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: 85,
          quantity_unit: 'cartons',
          quantity_raw: '85 cartons (箱)',
        }),
        extractionConfidence: 0.95,
        shipmentId: 'ship-005',
        isMatched: true,
        processingStatus: 'COMPLETED',
        reviewStatus: 'AUTO_ACCEPTED',
        isRead: true,
      },
      {
        id: 'email-002',
        messageId: '<dbl-100-100209@torque-shipair.com>',
        subject: '请核对提单 / Draft B/L - 100-100209',
        sender: 'docs@torque-shipair.com',
        receivedAt: daysAgo(2),
        bodyText: `Hi Sunny,\n\n请核对以下提单草稿 (Please verify the following Draft B/L):\n\nPO: 100-100209\nHBL Number: SZTOR88412\nCustomer: New Lobster UK\nShipper: Cobalt Knitwear Ltd.\nConsignee: New Lobster Ltd, London, UK\n\nRoute: Shenzhen → UK (SZ→UK)\nVessel: OOCL PIRAEUS\nVoyage: 215E\nCFS Cut-off: Already passed\nETD: 2026-04-25\nETA: 2026-05-25\n\nCargo Description:\n- 120 cartons knitted garments\n- Gross Weight: 2,400 KG\n- CBM: 14.2\n\nPlease check and confirm the B/L details within 24 hours.\n如有任何错误请尽快回复。\n\nThank you,\nTorque/Shipair Documentation Team`,
        emailType: 'DRAFT_BL',
        extractedData: JSON.stringify({
          po_numbers: ['100-100209'],
          customer: 'New Lobster UK',
          forwarder: 'Torque/Shipair',
          route: 'SZ→UK',
          booking_no: 'MAEU-742931847',
          so_number: 'SO-NLOB-001',
          item_style_no: 'ST-AW26-001',
          consignee_name: 'New Lobster Ltd',
          consignee_address: '45 Market Street, London EC3R 8BU, UK',
          hbl_number: 'SZTOR88412',
          mbl_number: null,
          container_no: 'MSKU-7281945',
          vessel: 'OOCL PIRAEUS',
          voyage_number: '215E',
          etd: '2026-04-25',
          eta: '2026-05-25',
          crd: null,
          cfs_cutoff: null,
          warehouse_address: 'Yantian CFS Terminal, Gate 3',
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: 120,
          quantity_unit: 'cartons',
          quantity_raw: '120 cartons',
        }),
        extractionConfidence: 0.92,
        shipmentId: 'ship-001',
        isMatched: true,
        processingStatus: 'COMPLETED',
        reviewStatus: 'AUTO_ACCEPTED',
        isRead: true,
      },
      {
        id: 'email-003',
        messageId: '<fbl-sz2c54172564@gfs-logistics.com>',
        subject: '开船提单 / Final B/L Issued - HBL SZ2C54172564',
        sender: 'billing@gfs-logistics.com',
        receivedAt: daysAgo(5),
        bodyText: `Dear Cobalt,\n\n开船提单已签发。Final Bill of Lading has been issued for the below shipment:\n\nPO: 2238941\nHBL: SZ2C54172564\nCustomer: SKIM US West\n\nVessel: CMA CGM MARCO POLO\nVoyage: 142E\nPort of Loading: Yantian, Shenzhen\nPort of Discharge: Los Angeles, CA\n\nETD: 2026-04-15\nETA: 2026-05-05\n\nThe vessel has departed as scheduled. Freight charges have been settled.\n\nPlease keep this B/L for your records.\n\nRegards,\nGFS Billing Department\nbilling@gfs-logistics.com`,
        emailType: 'FINAL_BL',
        extractedData: JSON.stringify({
          po_numbers: ['2238941'],
          customer: 'SKIM US West',
          forwarder: 'GFS',
          route: 'SZ→LA',
          booking_no: 'OOLU-S6209384',
          so_number: 'SO-SKIM-002',
          item_style_no: 'ST-SS26-402',
          consignee_name: 'SKIM Inc.',
          consignee_address: '8200 Wilshire Blvd, Los Angeles, CA 90048, USA',
          hbl_number: 'SZ2C54172564',
          mbl_number: 'CMDUSZ2026205',
          container_no: 'TCLU-5938201',
          vessel: 'CMA CGM MARCO POLO',
          voyage_number: '142E',
          etd: '2026-04-15',
          eta: '2026-05-05',
          crd: null,
          cfs_cutoff: null,
          warehouse_address: null,
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: null,
          quantity_unit: null,
          quantity_raw: null,
        }),
        extractionConfidence: 0.97,
        shipmentId: 'ship-002',
        isMatched: true,
        processingStatus: 'COMPLETED',
        reviewStatus: 'AUTO_ACCEPTED',
        isRead: true,
      },
      {
        id: 'email-004',
        messageId: '<telex-hkhbg34521@logwin.com>',
        subject: '电放提单 / Telex Release - 6131180898 - HK→DE',
        sender: 'release@logwin.com',
        receivedAt: daysAgo(3),
        bodyText: `Dear Cobalt Knitwear,\n\n电放提单确认 - Telex Release Confirmation\n\nWe confirm the telex release for the following shipment:\n\nPO: 6131180898\nHBL: HKHBG34521\nCustomer: Daniels DE\n\nCargo: 500 pieces (件) knitwear\nGross Weight: 3,200 KG\n\nVessel: MAERSK SELETAR\nVoyage: 426W\nRoute: HK→DE (Hong Kong → Hamburg)\n\nThe original B/L has been surrendered at origin and the consignee\nmay collect cargo at destination without presenting the original B/L.\n\nFreight Status: PAID IN FULL\nRelease Date: 2026-04-10\n\nPlease advise your customer accordingly.\n\nBest regards,\nLogwin Release Department`,
        emailType: 'TELEX_RELEASE',
        extractedData: JSON.stringify({
          po_numbers: ['6131180898'],
          customer: 'Daniels DE',
          forwarder: 'Logwin',
          route: 'HK→DE',
          booking_no: 'HLCU-BK8847210',
          so_number: 'SO-DANL-003',
          item_style_no: 'ST-AW26-505',
          consignee_name: 'Daniels GmbH',
          consignee_address: 'Hafenstraße 12, 20457 Hamburg, Germany',
          hbl_number: 'HKHBG34521',
          mbl_number: 'MAEUHK2026109',
          container_no: 'MSCU-4412830',
          vessel: 'MAERSK SELETAR',
          voyage_number: '426W',
          etd: null,
          eta: null,
          crd: null,
          cfs_cutoff: null,
          warehouse_address: 'Hong Kong International Terminal, Berth 5',
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: 500,
          quantity_unit: 'pieces',
          quantity_raw: '500 pieces (件)',
        }),
        extractionConfidence: 0.96,
        shipmentId: 'ship-003',
        isMatched: true,
        processingStatus: 'COMPLETED',
        reviewStatus: 'AUTO_ACCEPTED',
        isRead: true,
      },
      {
        id: 'email-005',
        messageId: '<delay-22491-22492@jas-forwarding.com>',
        subject: 'VESSEL DELAY NOTICE - PO 22491 / 22492 - Schedule Change',
        sender: 'ops@jas-forwarding.com',
        receivedAt: daysAgo(3),
        bodyText: `Dear Cobalt Operations,\n\nIMPORTANT: Vessel Delay / Schedule Change\n\nWe regret to inform you that the vessel originally scheduled for the\nbelow shipment has been rolled over due to port congestion.\n\nPO Numbers: 22491, 22492\nCustomer: Daniels DE\nHBL: SZJAS98712\nRoute: SZ→DE\n\nCargo: 360 cartons (总共360箱)\n\nOriginal vessel: EVER LUCKY / Voyage 088W\nNew vessel: To be confirmed (TBC)\n\nThe new schedule is being confirmed with the shipping line. We expect\nan updated ETD within the next 48 hours.\n\nWe apologize for any inconvenience.\n\nBest regards,\nJAS Forwarding Operations\nShenzhen Office`,
        emailType: 'DELAY_NOTICE',
        extractedData: JSON.stringify({
          po_numbers: ['22491', '22492'],
          customer: 'Daniels DE',
          forwarder: 'JAS Forwarding',
          route: 'SZ→DE',
          booking_no: 'MSCU-6150274',
          so_number: 'SO-DANL-004A',
          item_style_no: 'ST-SS26-710',
          consignee_name: 'Daniels GmbH',
          consignee_address: 'Hafenstraße 12, 20457 Hamburg, Germany',
          hbl_number: 'SZJAS98712',
          mbl_number: null,
          container_no: null,
          vessel: 'EVER LUCKY',
          voyage_number: '088W',
          etd: null,
          eta: null,
          crd: null,
          cfs_cutoff: null,
          warehouse_address: 'Shekou CFS Yard 4',
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: 360,
          quantity_unit: 'cartons',
          quantity_raw: '360 cartons (总共360箱)',
        }),
        extractionConfidence: 0.65,
        shipmentId: 'ship-004',
        isMatched: true,
        processingStatus: 'COMPLETED',
        reviewStatus: 'NEEDS_REVIEW',
      },
      {
        id: 'email-006',
        messageId: '<booking-test9999@gfs-logistics.com>',
        subject: '订舱确认 / Booking Confirmation - NEW PO# TEST-9999',
        sender: 'bookings@gfs-logistics.com',
        receivedAt: daysAgo(1),
        bodyText: `Hi Cobalt Team,\n\nBooking Confirmation / 订舱确认\n\nWe have received your booking request for:\n\nPO: TEST-9999\nCustomer: Test Customer\nRoute: SZ→AU (Shenzhen → Sydney)\n\nEstimated CRD: 2026-05-01\nCFS Cut-off: 2026-05-08\nETD: 2026-05-10\nETA: 2026-05-28\n\nVessel: MSC ANNA\nVoyage: FD612\n\nBooking has been confirmed with the shipping line. We will send\nthe Shipping Order / 入仓单 once warehouse details are finalized.\n\nThank you,\nGFS Bookings`,
        emailType: 'BOOKING_REQUEST',
        extractedData: JSON.stringify({
          po_numbers: ['TEST-9999'],
          customer: 'Test Customer',
          forwarder: 'GFS',
          route: 'SZ→AU',
          booking_no: null,
          so_number: null,
          item_style_no: null,
          consignee_name: null,
          consignee_address: null,
          hbl_number: null,
          mbl_number: null,
          container_no: null,
          vessel: 'MSC ANNA',
          voyage_number: 'FD612',
          etd: '2026-05-10',
          eta: '2026-05-28',
          crd: '2026-05-01',
          cfs_cutoff: '2026-05-08',
          warehouse_address: null,
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: null,
          quantity_unit: null,
          quantity_raw: null,
        }),
        extractionConfidence: 0.42,
        shipmentId: 'ship-008',
        isMatched: true,
        processingStatus: 'COMPLETED',
        reviewStatus: 'NEEDS_REVIEW',
      },
      {
        id: 'email-007',
        messageId: '<holiday-apr2026@cobalt.hk>',
        subject: 'Office Holiday Schedule - April 2026',
        sender: 'hr@cobalt.hk',
        receivedAt: daysAgo(7),
        bodyText: `Dear All,\n\nPlease note the following public holidays for April 2026:\n\n- April 4 (Friday): Ching Ming Festival\n- April 18 (Friday): Good Friday\n- April 21 (Monday): Easter Monday\n\nThe office will be closed on these dates. Please plan your shipping\nschedules accordingly.\n\nHR Department\nCobalt Knitwear`,
        emailType: 'OTHER',
        extractedData: null,
        extractionConfidence: null,
        shipmentId: null,
        isMatched: false,
        processingStatus: 'COMPLETED',
        reviewStatus: 'AUTO_ACCEPTED',
        isRead: true,
      },
      // ── Additional review queue emails ──────────────────────────
      {
        id: 'email-008',
        messageId: '<so-amb-wh-7891@dhl-gf.com>',
        subject: 'RE: 入仓单 / Shipping Order - PO# NL-2026-0112 - Warehouse TBC',
        sender: 'ops-sz@dhl-gf.com',
        receivedAt: daysAgo(1),
        bodyText: `Dear Cobalt,\n\nPlease find the shipping order below. Note: warehouse address is to be confirmed — the CFS terminal is changing locations next week.\n\nPO: NL-2026-0112\nCustomer: New Lobster UK\nForwarder: DHL Global Forwarding\nRoute: SZ→UK\n\nCargo: 95 cartons knitwear\nGross Weight: 1,850 KG\nCBM: 9.2\n\nVessel: COSCO SHIPPING ALPS\nVoyage: 041W\nETD: 2026-05-05\nETA: 2026-06-02\n\nWarehouse: (address pending — see attached map for tentative location)\nCFS Cut-off: 2026-05-03 16:00\n\nPlease confirm you can deliver before cut-off.\n\nRegards,\nDHL GF Shenzhen`,
        emailType: 'SHIPPING_ORDER',
        extractedData: JSON.stringify({
          po_numbers: ['NL-2026-0112'],
          customer: 'New Lobster UK',
          forwarder: 'DHL Global Forwarding',
          route: 'SZ→UK',
          booking_no: 'MAEU-742931900',
          so_number: null,
          item_style_no: null,
          consignee_name: 'New Lobster Ltd',
          consignee_address: '45 Market Street, London EC3R 8BU, UK',
          hbl_number: null,
          mbl_number: null,
          container_no: null,
          vessel: 'COSCO SHIPPING ALPS',
          voyage_number: '041W',
          etd: '2026-05-05',
          eta: '2026-06-02',
          crd: null,
          cfs_cutoff: '2026-05-03',
          warehouse_address: '(pending)',
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: 95,
          quantity_unit: 'cartons',
          quantity_raw: '95 cartons knitwear',
        }),
        extractionConfidence: 0.72,
        shipmentId: 'ship-001',
        isMatched: true,
        processingStatus: 'COMPLETED',
        reviewStatus: 'NEEDS_REVIEW',
      },
      {
        id: 'email-009',
        messageId: '<dbl-scan-poor@torque-shipair.com>',
        subject: '请核对提单 / Draft B/L - Scanned Copy - PO 2238942',
        sender: 'docs@torque-shipair.com',
        receivedAt: daysAgo(2),
        bodyText: `Hi Sunny,\n\n请看附件 (Please see attachment). This is a scanned copy of the Draft B/L. Apologies for the low quality — the original was faxed to us.\n\nPO: 2238942 (we think — hard to read)\nHBL: SZT0R??412 (partially illegible)\nCustomer: SKIM US West (or S.KIM US?)\n\nVessel: unclear from scan\nRoute: SZ→LA\n\nPlease confirm if you can read the details from the attached scan.\n\n谢谢,\nTorque/Shipair Docs`,
        emailType: 'DRAFT_BL',
        extractedData: JSON.stringify({
          po_numbers: ['2238942'],
          customer: 'SKIM US West',
          forwarder: 'Torque/Shipair',
          route: 'SZ→LA',
          booking_no: null,
          so_number: null,
          item_style_no: null,
          consignee_name: 'SKIM Inc.',
          consignee_address: null,
          hbl_number: 'SZT0R??412',
          mbl_number: null,
          container_no: null,
          vessel: null,
          voyage_number: null,
          etd: null,
          eta: null,
          crd: null,
          cfs_cutoff: null,
          warehouse_address: null,
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: null,
          quantity_unit: null,
          quantity_raw: null,
        }),
        extractionConfidence: 0.55,
        shipmentId: 'ship-002',
        isMatched: true,
        processingStatus: 'COMPLETED',
        reviewStatus: 'NEEDS_REVIEW',
      },
      {
        id: 'email-010',
        messageId: '<booking-incomplete@abc-freight.com>',
        subject: 'Booking Request - Urgent - No PO yet',
        sender: 'rush@abc-freight.com',
        receivedAt: daysAgo(0),
        bodyText: `Hi Cobalt,\n\nWe need to book urgently for a new customer. Details are incomplete but we need to reserve space ASAP:\n\nCustomer: TBC (new account, paperwork in progress)\nDestination: Japan\nCargo: approx. 40 cartons, small knitwear order\n\nPlease book on any available vessel from Shenzhen to Tokyo/Yokohama in the next 10 days.\n\nWill send PO and full details shortly.\n\nThanks,\nABC Freight`,
        emailType: 'BOOKING_REQUEST',
        extractedData: JSON.stringify({
          po_numbers: [],
          customer: null,
          forwarder: 'ABC Freight',
          route: 'SZ→JP',
          booking_no: null,
          so_number: null,
          item_style_no: null,
          consignee_name: null,
          consignee_address: null,
          hbl_number: null,
          mbl_number: null,
          container_no: null,
          vessel: null,
          voyage_number: null,
          etd: null,
          eta: null,
          crd: null,
          cfs_cutoff: null,
          warehouse_address: null,
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: 40,
          quantity_unit: 'cartons',
          quantity_raw: 'approx. 40 cartons',
        }),
        extractionConfidence: 0.38,
        shipmentId: null,
        isMatched: false,
        processingStatus: 'COMPLETED',
        reviewStatus: 'NEEDS_REVIEW',
      },
      {
        id: 'email-011',
        messageId: '<fbl-multi-po@gfs-logistics.com>',
        subject: '开船提单 / Final B/L - Multiple POs Consolidated - SZ→US',
        sender: 'billing@gfs-logistics.com',
        receivedAt: daysAgo(4),
        bodyText: `Dear Cobalt,\n\nFinal B/L has been issued for the consolidated shipment:\n\nPO Numbers: ML-2026-0045, ML-2026-0046, ML-2026-0047\n(Note: these 3 POs are consolidated into a single container)\n\nHBL: SZ2C54172999\nMBL: CMDUSZ2026210\nContainer: TCLU-5938205\n\nCustomer: Marine Layer US\nRoute: SZ→LA\nVessel: CMA CGM MARCO POLO\nVoyage: 143E\nETD: 2026-04-28\nETA: 2026-05-18\n\nTotal: 250 cartons, 5,000 KG, 28.5 CBM\n\nPlease note the consolidation — all three POs ship on this single B/L.\n\nRegards,\nGFS Billing`,
        emailType: 'FINAL_BL',
        extractedData: JSON.stringify({
          po_numbers: ['ML-2026-0045', 'ML-2026-0046', 'ML-2026-0047'],
          customer: 'Marine Layer US',
          forwarder: 'GFS',
          route: 'SZ→US',
          booking_no: 'EGLV-102938574',
          so_number: null,
          item_style_no: null,
          consignee_name: 'Marine Layer Inc.',
          consignee_address: '580 Howard St, San Francisco, CA 94105, USA',
          hbl_number: 'SZ2C54172999',
          mbl_number: 'CMDUSZ2026210',
          container_no: 'TCLU-5938205',
          vessel: 'EVER GOLDEN',
          voyage_number: '143E',
          etd: '2026-04-28',
          eta: '2026-05-18',
          crd: null,
          cfs_cutoff: null,
          warehouse_address: null,
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: 250,
          quantity_unit: 'cartons',
          quantity_raw: '250 cartons',
        }),
        extractionConfidence: 0.61,
        shipmentId: 'ship-005',
        isMatched: true,
        processingStatus: 'COMPLETED',
        reviewStatus: 'NEEDS_REVIEW',
      },
      {
        id: 'email-012',
        messageId: '<so-cn-only-5501@cosco-logistics.com>',
        subject: '入仓通知 - PO# 5501-HK-AU - 请安排入仓',
        sender: 'warehouse@cosco-logistics.com',
        receivedAt: daysAgo(1),
        bodyText: `你好 Cobalt 团队，\n\n以下是入仓通知，请安排货物入仓。\n\n客户编号：5501-HK-AU\n客户名称：Woolworths AU\n货代：COSCO Logistics\n路线：HK→AU（香港→悉尼）\n\n货物详情：\n- 200箱 针织品\n- 毛重：4,200公斤\n- 体积：24.0立方米\n\n仓库地址：葵涌货柜码头 CT8 仓库\n截仓时间：2026-05-12 15:00\n\n船名：COSCO SHIPPING PISCES\n航次号：055E\n预计开船：2026-05-14\n预计到港：2026-06-01\n\n请务必在截仓时间前安排入仓。\n\n谢谢，\nCOSCO Logistics 仓储部`,
        emailType: 'SHIPPING_ORDER',
        extractedData: JSON.stringify({
          po_numbers: ['5501-HK-AU'],
          customer: 'Woolworths AU',
          forwarder: 'COSCO Logistics',
          route: 'HK→AU',
          booking_no: 'COSU-3392O18E',
          so_number: null,
          item_style_no: null,
          consignee_name: 'Woolworths Group Ltd',
          consignee_address: '1 Woolworths Way, Bella Vista NSW 2153, Australia',
          hbl_number: null,
          mbl_number: null,
          container_no: null,
          vessel: 'COSCO SHIPPING PISCES',
          voyage_number: '0S5E',
          etd: '2026-05-14',
          eta: '2026-06-01',
          crd: null,
          cfs_cutoff: '2026-05-12',
          warehouse_address: '葵涌货柜码头 CT8 仓库',
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: 200,
          quantity_unit: 'cartons',
          quantity_raw: '200箱 针织品',
        }),
        extractionConfidence: 0.62,
        shipmentId: 'ship-007',
        isMatched: true,
        processingStatus: 'COMPLETED',
        reviewStatus: 'NEEDS_REVIEW',
      },
      {
        id: 'email-013',
        messageId: '<delay-vague-port@maersk-ops.com>',
        subject: 'Schedule Advisory - Possible Delay - Multiple Vessels',
        sender: 'advisory@maersk-ops.com',
        receivedAt: daysAgo(2),
        bodyText: `Dear Valued Customer,\n\nDue to ongoing port congestion at Yantian and Shekou terminals, several vessels may experience delays of 3-7 days.\n\nAffected routes: SZ→EU, SZ→UK, HK→DE\n\nWe are unable to confirm specific vessel impacts at this time. Please check our online tracking portal for real-time updates.\n\nAffected POs may include recent bookings through our Shenzhen office. We will send individual notifications once the situation is clearer.\n\nWe apologize for the inconvenience.\n\nMaersk Operations Advisory\nSouth China Region`,
        emailType: 'DELAY_NOTICE',
        extractedData: JSON.stringify({
          po_numbers: [],
          customer: null,
          forwarder: 'Maersk',
          route: null,
          booking_no: null,
          so_number: null,
          item_style_no: null,
          consignee_name: null,
          consignee_address: null,
          hbl_number: null,
          mbl_number: null,
          container_no: null,
          vessel: null,
          voyage_number: null,
          etd: null,
          eta: null,
          crd: null,
          cfs_cutoff: null,
          warehouse_address: null,
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: null,
          quantity_unit: null,
          quantity_raw: null,
        }),
        extractionConfidence: 0.48,
        shipmentId: null,
        isMatched: false,
        processingStatus: 'COMPLETED',
        reviewStatus: 'NEEDS_REVIEW',
      },
      {
        id: 'email-014',
        messageId: '<dbl-reviewed-ok@torque-shipair.com>',
        subject: '请核对提单 / Draft B/L - PO# 6131180899 - HK→US',
        sender: 'docs@torque-shipair.com',
        receivedAt: daysAgo(6),
        bodyText: `Hi Sunny,\n\nDraft B/L for your review:\n\nPO: 6131180899\nHBL: HKTOR55231\nCustomer: Daniels US\nRoute: HK→US\n\nVessel: OOCL HONG KONG\nVoyage: 330E\nETD: 2026-04-10\nETA: 2026-04-30\n\nCargo: 180 cartons, 3,600 KG\n\nPlease confirm within 24h.\n\nThanks,\nTorque/Shipair Docs`,
        emailType: 'DRAFT_BL',
        extractedData: JSON.stringify({
          po_numbers: ['6131180899'],
          customer: 'Daniels DE',
          forwarder: 'Torque/Shipair',
          route: 'HK→DE',
          booking_no: 'HLCU-BK8847210',
          so_number: 'SO-DANL-899',
          item_style_no: 'ST-SS26-899',
          consignee_name: 'Daniels GmbH',
          consignee_address: 'Friedrichstraße 68, 10117 Berlin, Germany',
          hbl_number: 'HKTOR55231',
          mbl_number: null,
          container_no: 'OOLU-7382910',
          vessel: 'MAERSK SELETAR',
          voyage_number: '330E',
          etd: '2026-04-10',
          eta: '2026-04-30',
          crd: null,
          cfs_cutoff: null,
          warehouse_address: 'HK Container Port, Terminal 9',
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: 180,
          quantity_unit: 'cartons',
          quantity_raw: '180 cartons',
        }),
        extractionConfidence: 0.88,
        shipmentId: 'ship-003',
        isMatched: true,
        processingStatus: 'COMPLETED',
        reviewStatus: 'REVIEWED_OK',
        isRead: true,
        reviewedBy: 'user-sunny',
        reviewedAt: daysAgo(5),
      },
      {
        id: 'email-015',
        messageId: '<booking-corrected@gfs-logistics.com>',
        subject: '订舱确认 / Booking Confirmation - PO# WW-AU-8801',
        sender: 'bookings@gfs-logistics.com',
        receivedAt: daysAgo(5),
        bodyText: `Hi Cobalt Team,\n\nBooking Confirmation:\n\nPO: WW-AU-8801\nCustomer: Woolworths AU\nRoute: SZ→AU\nVessel: MSC ANNA\nVoyage: FD615\nETD: 2026-05-15\nETA: 2026-06-02\n\nCargo: 150 cartons knitwear, 3,000 KG\n\nBooking confirmed with MSC. Shipping order to follow.\n\nThanks,\nGFS Bookings`,
        emailType: 'BOOKING_REQUEST',
        extractedData: JSON.stringify({
          po_numbers: ['WW-AU-8801'],
          customer: 'Woolworths AU',
          forwarder: 'COSCO Logistics',
          route: 'HK→AU',
          booking_no: 'COSU-3392018E',
          so_number: null,
          item_style_no: null,
          consignee_name: 'Woolworths Group Ltd',
          consignee_address: '1 Woolworths Way, Bella Vista NSW 2153, Australia',
          hbl_number: null,
          mbl_number: null,
          container_no: null,
          vessel: 'COSCO SHIPPING PISCES',
          voyage_number: '055E',
          etd: '2026-05-14',
          eta: '2026-06-01',
          crd: null,
          cfs_cutoff: null,
          warehouse_address: null,
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: 150,
          quantity_unit: 'cartons',
          quantity_raw: '150 cartons knitwear',
        }),
        extractionConfidence: 0.73,
        shipmentId: 'ship-007',
        isMatched: true,
        processingStatus: 'COMPLETED',
        reviewStatus: 'REVIEWED_CORRECTED',
        isRead: true,
        reviewedBy: 'user-sunny',
        reviewedAt: daysAgo(4),
        reviewNotes: 'Corrected customer name from "Woolsworth" to "Woolworths AU", fixed route from SZ→UK to HK→AU, updated vessel/booking to match shipment',
        originalExtractedData: JSON.stringify({
          po_numbers: ['WW-AU-8801'],
          customer: 'Woolsworth',
          forwarder: 'GFS',
          route: 'SZ→UK',
          booking_no: 'COSU-3392044F',
          so_number: null,
          item_style_no: null,
          consignee_name: 'Woolworths Group Ltd',
          consignee_address: '1 Woolworths Way, Bella Vista NSW 2153, Australia',
          hbl_number: null,
          mbl_number: null,
          container_no: null,
          vessel: 'MSC ANNA',
          voyage_number: 'FD615',
          etd: '2026-05-15',
          eta: '2026-06-02',
          crd: null,
          cfs_cutoff: null,
          warehouse_address: null,
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: 150,
          quantity_unit: 'cartons',
          quantity_raw: '150 cartons knitwear',
        }),
      },
      {
        id: 'email-016',
        messageId: '<telex-missing-hbl@logwin.com>',
        subject: '电放提单 / Telex Release - PO# SK-2026-3301 - Missing HBL',
        sender: 'release@logwin.com',
        receivedAt: daysAgo(1),
        bodyText: `Dear Cobalt,\n\nTelex Release Confirmation:\n\nPO: SK-2026-3301\nCustomer: SKIM US West\nHBL: (to be issued — original not yet received from carrier)\n\nRoute: SZ→LA\nVessel: EVER GIVEN\nVoyage: 102W\n\nCargo: 75 cartons, 1,500 KG\n\nNote: The HBL number is pending. We have received verbal confirmation of the telex release but the formal document is delayed. We will send the updated notice once the HBL is issued.\n\nRegards,\nLogwin Release Department`,
        emailType: 'TELEX_RELEASE',
        extractedData: JSON.stringify({
          po_numbers: ['SK-2026-3301'],
          customer: 'SKIM US West',
          forwarder: 'Logwin',
          route: 'SZ→LA',
          booking_no: null,
          so_number: null,
          item_style_no: null,
          consignee_name: 'SKIM Inc.',
          consignee_address: '8200 Wilshire Blvd, Los Angeles, CA 90048, USA',
          hbl_number: null,
          mbl_number: null,
          container_no: null,
          vessel: 'EVER GIVEN',
          voyage_number: '102W',
          etd: null,
          eta: null,
          crd: null,
          cfs_cutoff: null,
          warehouse_address: null,
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: 75,
          quantity_unit: 'cartons',
          quantity_raw: '75 cartons',
        }),
        extractionConfidence: 0.58,
        shipmentId: 'ship-002',
        isMatched: true,
        processingStatus: 'COMPLETED',
        reviewStatus: 'NEEDS_REVIEW',
      },
      {
        id: 'email-017',
        messageId: '<so-date-conflict@dhl-gf.com>',
        subject: 'RE: Shipping Order - PO# DAN-2026-7710 - Date Conflict',
        sender: 'ops-hk@dhl-gf.com',
        receivedAt: daysAgo(0),
        bodyText: `Dear Cobalt,\n\nShipping Order for the below. Please note the dates may need verification — the carrier originally quoted ETD April 30 but has since updated to May 2. The system still shows the old date.\n\nPO: DAN-2026-7710\nCustomer: Daniels DE\nRoute: HK→DE\n\nCargo: 310 cartons knitwear\nGross Weight: 6,200 KG\nCBM: 35.5\n\nVessel: MAERSK EDINBURGH\nVoyage: 518W\nETD: 2026-04-30 (possibly 2026-05-02)\nETA: 2026-06-08 (or 2026-06-10?)\n\nCFS Cut-off: 2026-04-28\nWarehouse: HK International Terminal, Berth 7\n\nPlease double-check with the carrier.\n\nRegards,\nDHL GF Hong Kong`,
        emailType: 'SHIPPING_ORDER',
        extractedData: JSON.stringify({
          po_numbers: ['DAN-2026-7710'],
          customer: 'Daniels DE',
          forwarder: 'DHL Global Forwarding',
          route: 'HK→DE',
          booking_no: 'HLCU-BK8847120',
          so_number: null,
          item_style_no: 'ST-AW26-710',
          consignee_name: 'Daniels GmbH',
          consignee_address: 'Hafenstraße 12, 20457 Hamburg, Germany',
          hbl_number: null,
          mbl_number: null,
          container_no: null,
          vessel: 'MAERSK EDINBURGH',
          voyage_number: '518W',
          etd: '2026-04-30',
          eta: '2026-06-08',
          crd: null,
          cfs_cutoff: '2026-04-28',
          warehouse_address: 'HK International Terminal, Berth 7',
          warehouse_start_date: null,
          warehouse_end_date: null,
          in_dc_date: null,
          quantity: 310,
          quantity_unit: 'cartons',
          quantity_raw: '310 cartons knitwear',
        }),
        extractionConfidence: 0.69,
        shipmentId: 'ship-003',
        isMatched: true,
        processingStatus: 'COMPLETED',
        reviewStatus: 'NEEDS_REVIEW',
      },
    ])
    console.log('  Seeded 17 emails')
  }

  // ============================================
  // Sample Purchase Orders
  // ============================================
  const existingPOs = await db.select().from(purchaseOrders)
  if (existingPOs.length === 0) {
    const now = new Date()
    await db.insert(purchaseOrders).values([
      {
        id: 'po-001',
        poNumber: '100-100209',
        customerId: 'cust-001',
        vendorId: 'vnd-001',
        totalQuantity: 350,
        quantityUnit: 'cartons',
        notes: 'New Lobster UK — AW26 knitwear collection',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'po-001b',
        poNumber: '100-100210',
        customerId: 'cust-001',
        vendorId: 'vnd-001',
        totalQuantity: 150,
        quantityUnit: 'cartons',
        notes: 'New Lobster UK — AW26 accessories',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'po-001c',
        poNumber: '100-100215',
        customerId: 'cust-001',
        vendorId: 'vnd-002',
        totalQuantity: 80,
        quantityUnit: 'cartons',
        notes: 'New Lobster UK — AW26 outerwear',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'po-002',
        poNumber: '2238941',
        customerId: 'cust-002',
        vendorId: 'vnd-002',
        totalQuantity: 200,
        quantityUnit: 'cartons',
        notes: 'SKIM US West — SS26 basics range',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'po-002b',
        poNumber: '2238942',
        customerId: 'cust-002',
        vendorId: 'vnd-002',
        totalQuantity: 120,
        quantityUnit: 'cartons',
        notes: 'SKIM US West — SS26 swim range',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'po-003',
        poNumber: '6131180898',
        customerId: 'cust-003',
        vendorId: 'vnd-001',
        totalQuantity: 500,
        quantityUnit: 'pieces',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'po-003b',
        poNumber: '6131180899',
        customerId: 'cust-003',
        vendorId: 'vnd-001',
        totalQuantity: 300,
        quantityUnit: 'pieces',
        notes: 'Daniels DE — same vessel consolidation',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'po-004',
        poNumber: '22491',
        customerId: 'cust-003',
        vendorId: 'vnd-003',
        totalQuantity: 180,
        quantityUnit: 'cartons',
        notes: 'Daniels DE — partial shipment 1 of 2',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'po-005',
        poNumber: '22492',
        customerId: 'cust-003',
        vendorId: 'vnd-003',
        totalQuantity: 180,
        quantityUnit: 'cartons',
        notes: 'Daniels DE — partial shipment 2 of 2',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'po-006',
        poNumber: 'ML-2026-0045',
        customerId: 'cust-004',
        vendorId: 'vnd-002',
        totalQuantity: 85,
        quantityUnit: 'cartons',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'po-007',
        poNumber: 'FEN-MS-118997',
        customerId: 'cust-005',
        vendorId: 'vnd-004',
        totalQuantity: 40,
        quantityUnit: 'cbm',
        createdAt: now,
        updatedAt: now,
      },
      // ship-007: Woolworths AU — 2 POs
      {
        id: 'po-008',
        poNumber: '5501-HK-AU',
        customerId: 'cust-006',
        vendorId: 'vnd-001',
        totalQuantity: 200,
        quantityUnit: 'cartons',
        notes: 'Woolworths AU — HK→AU knitwear',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'po-009',
        poNumber: 'WW-AU-8801',
        customerId: 'cust-006',
        vendorId: 'vnd-001',
        totalQuantity: 150,
        quantityUnit: 'cartons',
        notes: 'Woolworths AU — SZ→AU booking',
        createdAt: now,
        updatedAt: now,
      },
      // ship-008: Test Customer — 1 PO
      {
        id: 'po-010',
        poNumber: 'TEST-9999',
        customerId: null,
        vendorId: null,
        totalQuantity: null,
        quantityUnit: null,
        notes: 'Test Customer — new account, details TBC',
        createdAt: now,
        updatedAt: now,
      },
    ])
    console.log('  Seeded 14 purchase orders')

    // Link POs to shipments
    await db.insert(shipmentPos).values([
      // Ship-001: New Lobster UK — 3 POs consolidated into 1 container
      { id: 'spo-001', shipmentId: 'ship-001', poId: 'po-001', quantity: 120, createdAt: now },
      { id: 'spo-001b', shipmentId: 'ship-001', poId: 'po-001b', quantity: 150, createdAt: now },
      { id: 'spo-001c', shipmentId: 'ship-001', poId: 'po-001c', quantity: 80, createdAt: now },
      // Ship-002: SKIM — 2 POs on same vessel
      { id: 'spo-002', shipmentId: 'ship-002', poId: 'po-002', quantity: 200, createdAt: now },
      { id: 'spo-002b', shipmentId: 'ship-002', poId: 'po-002b', quantity: 120, createdAt: now },
      // Ship-003: Daniels sailed — 2 POs consolidated
      { id: 'spo-003', shipmentId: 'ship-003', poId: 'po-003', quantity: 500, createdAt: now },
      { id: 'spo-003b', shipmentId: 'ship-003', poId: 'po-003b', quantity: 300, createdAt: now },
      // Ship-004: Daniels delayed — 2 POs (existing)
      { id: 'spo-004', shipmentId: 'ship-004', poId: 'po-004', quantity: 180, createdAt: now },
      { id: 'spo-005', shipmentId: 'ship-004', poId: 'po-005', quantity: 180, createdAt: now },
      // Ship-005: Marine Layer — 1 PO
      { id: 'spo-006', shipmentId: 'ship-005', poId: 'po-006', quantity: 85, createdAt: now },
      // Ship-006: Fenwick — 1 PO
      { id: 'spo-007', shipmentId: 'ship-006', poId: 'po-007', quantity: 40, createdAt: now },
      // Ship-007: Woolworths AU — 2 POs
      { id: 'spo-008', shipmentId: 'ship-007', poId: 'po-008', quantity: 200, createdAt: now },
      { id: 'spo-009', shipmentId: 'ship-007', poId: 'po-009', quantity: 150, createdAt: now },
      // Ship-008: Test Customer — 1 PO
      { id: 'spo-010', shipmentId: 'ship-008', poId: 'po-010', quantity: null, createdAt: now },
    ])
    console.log('  Seeded 14 PO-shipment links')

    // Sample history entries (to populate the timeline)
    const daysAgo = (d: number) => new Date(Date.now() - d * 86400000)
    await db.insert(shipmentHistory).values([
      {
        id: 'hist-001',
        shipmentId: 'ship-003',
        field: 'eta',
        oldValue: daysAgo(35).toISOString(),
        newValue: daysAgo(30).toISOString(),
        sourceType: 'email',
        sourceId: null,
        isDelay: false,
        notes: 'Updated from Final B/L',
        changedAt: daysAgo(5),
      },
      {
        id: 'hist-002',
        shipmentId: 'ship-004',
        field: 'vessel_name',
        oldValue: 'EVER LUCKY',
        newValue: null,
        sourceType: 'email',
        sourceId: null,
        isDelay: false,
        notes: 'Vessel rolled over — awaiting new assignment',
        changedAt: daysAgo(3),
      },
      {
        id: 'hist-003',
        shipmentId: 'ship-004',
        field: 'status',
        oldValue: 'AT_WAREHOUSE',
        newValue: 'AT_WAREHOUSE',
        sourceType: 'system',
        isDelay: true,
        notes: 'Delay detected: vessel rollover notification',
        changedAt: daysAgo(3),
      },
      {
        id: 'hist-004',
        shipmentId: 'ship-001',
        field: 'etd',
        oldValue: null,
        newValue: daysAgo(-15).toISOString(),
        sourceType: 'email',
        notes: 'ETD assigned from Draft B/L',
        changedAt: daysAgo(2),
      },
    ])
    console.log('  Seeded 4 history entries')
  }

  // ============================================
  // Sample Email Attachments
  // ============================================
  const existingAttachments = await db.select().from(emailAttachments)
  if (existingAttachments.length === 0) {
    await db.insert(emailAttachments).values([
      // email-001 (Shipping Order) — SO PDF
      {
        id: 'att-001',
        emailId: 'email-001',
        filename: 'SO_ML-2026-0045.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 245_760,
        content: null, // placeholder — agent would store base64 here
      },
      // email-002 (Draft B/L) — Draft B/L PDF
      {
        id: 'att-002',
        emailId: 'email-002',
        filename: 'Draft_BL_NL-SS26-112.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 312_000,
        content: null,
      },
      // email-002 (Draft B/L) — Packing List Excel
      {
        id: 'att-003',
        emailId: 'email-002',
        filename: 'Packing_List_NL-SS26-112.xlsx',
        mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        sizeBytes: 48_500,
        content: null,
      },
      // email-003 (Final B/L) — Final B/L PDF
      {
        id: 'att-004',
        emailId: 'email-003',
        filename: 'Final_BL_HC-2026-0812.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 289_000,
        content: null,
      },
      // email-004 (Telex Release) — Telex Release letter
      {
        id: 'att-005',
        emailId: 'email-004',
        filename: 'Telex_Release_100-100209.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 156_200,
        content: null,
      },
      // email-005 (Delay Notice) — Carrier notice PDF
      {
        id: 'att-006',
        emailId: 'email-005',
        filename: 'Delay_Notice_COSCO_2026-04.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 98_300,
        content: null,
      },
      // email-006 (Booking Request) — Booking confirmation + invoice
      {
        id: 'att-007',
        emailId: 'email-006',
        filename: 'Booking_Confirmation_ML-2026-0045.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 178_400,
        content: null,
      },
      {
        id: 'att-008',
        emailId: 'email-006',
        filename: 'Commercial_Invoice_ML-2026-0045.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 134_600,
        content: null,
      },
      // email-008 (SO with pending warehouse) — SO PDF + warehouse map
      {
        id: 'att-009',
        emailId: 'email-008',
        filename: 'SO_NL-2026-0112.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 198_300,
        content: null,
      },
      {
        id: 'att-010',
        emailId: 'email-008',
        filename: 'Warehouse_Map_Tentative.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 512_000,
        content: null,
      },
      // email-009 (scanned Draft B/L) — low-quality scan
      {
        id: 'att-011',
        emailId: 'email-009',
        filename: 'Draft_BL_Scan_2238942.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 1_245_000,
        content: null,
      },
      // email-011 (Final B/L multi-PO) — consolidated B/L + packing list
      {
        id: 'att-012',
        emailId: 'email-011',
        filename: 'Final_BL_Consolidated_ML-2026.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 345_200,
        content: null,
      },
      {
        id: 'att-013',
        emailId: 'email-011',
        filename: 'Packing_List_Consolidated.xlsx',
        mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        sizeBytes: 67_800,
        content: null,
      },
      // email-012 (Chinese-only SO) — SO PDF
      {
        id: 'att-014',
        emailId: 'email-012',
        filename: '入仓通知_5501-HK-AU.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 221_400,
        content: null,
      },
      // email-013 (vague delay) — advisory PDF
      {
        id: 'att-015',
        emailId: 'email-013',
        filename: 'Maersk_Schedule_Advisory_Apr2026.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 89_100,
        content: null,
      },
      // email-014 (reviewed OK) — Draft B/L PDF
      {
        id: 'att-016',
        emailId: 'email-014',
        filename: 'Draft_BL_6131180899.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 278_900,
        content: null,
      },
      // email-015 (reviewed corrected) — booking confirmation
      {
        id: 'att-017',
        emailId: 'email-015',
        filename: 'Booking_Confirmation_WW-AU-8801.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 167_500,
        content: null,
      },
      // email-016 (telex release missing HBL) — partial telex letter
      {
        id: 'att-018',
        emailId: 'email-016',
        filename: 'Telex_Release_Partial_SK-3301.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 112_300,
        content: null,
      },
      // email-017 (date conflict SO) — SO + carrier rate sheet
      {
        id: 'att-019',
        emailId: 'email-017',
        filename: 'SO_DAN-2026-7710.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 234_100,
        content: null,
      },
      {
        id: 'att-020',
        emailId: 'email-017',
        filename: 'Carrier_Rate_Sheet_Maersk_May2026.xlsx',
        mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        sizeBytes: 54_200,
        content: null,
      },
    ])
    console.log('  Seeded 20 email attachments')
  }

  console.log('Seeding complete!')
}

// Run seed when executed directly (e.g. `pnpm db:seed`), not when imported
const isDirectRun = process.argv[1]?.includes('seed.ts')
if (isDirectRun) {
  seed().catch(console.error)
}
