/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AlertRules {
  computeTz: Generated<string>;
  countryThresholds: string | null;
  description: string;
  enabled: Generated<boolean>;
  id: string;
  locked: Generated<boolean>;
  name: string;
  severity: string;
  state: string | null;
  thresholdHours: number;
  triggerReference: string;
  triggerType: string;
  updatedAt: Generated<Date>;
  watchFor: string;
}

export interface Alerts {
  bookingId: string | null;
  createdAt: Generated<Date>;
  dedupKey: string | null;
  dismissedAt: Date | null;
  firedAt: Generated<Date>;
  id: Generated<string>;
  message: string;
  readAt: Date | null;
  resolvedAt: Date | null;
  ruleId: string;
  severity: string;
  shipmentId: string | null;
  snoozedUntil: Date | null;
  status: Generated<string>;
}

export interface AppSettings {
  key: string;
  updatedAt: Generated<Date>;
  updatedBy: string | null;
  value: string;
}

export interface BookingPos {
  bookingId: string;
  createdAt: Generated<Date>;
  id: Generated<string>;
  poId: string;
}

export interface Bookings {
  brand: string | null;
  consigneeId: string | null;
  crd: Date | null;
  createdAt: Generated<Date>;
  customerId: string | null;
  forwarderId: string | null;
  id: Generated<string>;
  jobNo: string;
  notes: string | null;
  status: Generated<string>;
  updatedAt: Generated<Date>;
  vendorId: string | null;
}

export interface Carriers {
  createdAt: Generated<Date>;
  id: Generated<string>;
  name: string;
  scac: string;
  updatedAt: Generated<Date>;
}

export interface ChangeLog {
  actorUserId: string | null;
  changeType: string;
  createdAt: Generated<Date>;
  entityId: string;
  entityType: string;
  field: string | null;
  id: Generated<string>;
  isDelay: Generated<boolean>;
  newValue: string | null;
  note: string | null;
  oldValue: string | null;
  seq: Generated<number>;
  sourceId: string | null;
  sourceType: string;
}

export interface Consignees {
  address: string | null;
  createdAt: Generated<Date>;
  id: Generated<string>;
  mapsToCustomerId: string | null;
  name: string;
  updatedAt: Generated<Date>;
}

export interface Customers {
  address: string | null;
  code: string;
  contactEmail: string | null;
  country: string | null;
  createdAt: Generated<Date>;
  erpSyncedAt: Date | null;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Date>;
}

export interface EmailAttachment {
  createdAt: Generated<Date>;
  declaredMime: string | null;
  filename: string;
  graphAttachmentId: string | null;
  id: Generated<string>;
  messageId: string;
  rawBytes: Buffer | null;
  sizeBytes: Generated<number>;
  sourceKind: string | null;
}

export interface EmailMessage {
  attachmentCount: Generated<number>;
  bodyHtml: string | null;
  bodyText: string | null;
  ccRecipients: string | null;
  conversationId: string | null;
  createdAt: Generated<Date>;
  graphId: string | null;
  graphMessageId: string;
  id: Generated<string>;
  receivedAt: Date | null;
  sender: string | null;
  sourceFile: string | null;
  status: string | null;
  subject: string | null;
  toRecipients: string | null;
}

export interface EmailRead {
  messageId: string;
  readAt: Generated<Date>;
  readBy: string | null;
}

export interface FieldLocks {
  entityId: string;
  entityType: string;
  field: string;
  id: Generated<string>;
  lockedAt: Generated<Date>;
  lockedBy: string | null;
  lockedValue: string | null;
}

export interface ForwarderAliases {
  aliasType: string;
  createdAt: Generated<Date>;
  forwarderId: string;
  id: Generated<string>;
  value: string;
}

export interface Forwarders {
  code: string | null;
  createdAt: Generated<Date>;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Date>;
}

export interface IngestState {
  id: string;
  lastSyncAt: Date | null;
  updatedAt: Generated<Date>;
  watermark: Date | null;
}

export interface MasterResolution {
  active: Generated<boolean>;
  createdAt: Generated<Date>;
  createdBy: string | null;
  evidence: string | null;
  id: Generated<string>;
  kind: string;
  lhs: string;
  reason: string | null;
  reviewedAt: Date | null;
  reviewedBy: string | null;
  rhs: string | null;
  source: Generated<string>;
  status: Generated<string>;
  updatedAt: Generated<Date>;
}

export interface ParsedRecord {
  confidence: string | null;
  createdAt: Generated<Date>;
  emailType: string | null;
  fields: string | null;
  graphMessageId: string | null;
  id: Generated<string>;
  matchKeys: string | null;
  messageId: string;
  mode: string | null;
  parserAdapter: string | null;
  poNo: string | null;
  /** Normalized PO key (normKey(po_no) || normKey(match_keys.customer_po)) — index for commit enrichment. */
  poNoNorm: string | null;
  /** cobalt-queue soul version (queue.prompt_version.id) that produced this parse — provenance (0007). */
  promptVersion: number | null;
  recordIdx: Generated<number>;
  senderType: string | null;
}

export interface Ports {
  country: string | null;
  createdAt: Generated<Date>;
  iata: string | null;
  id: Generated<string>;
  mode: Generated<string>;
  name: string;
  unlocode: string;
}

export interface PurchaseOrders {
  brand: string | null;
  crd: Date | null;
  createdAt: Generated<Date>;
  customerId: string | null;
  erpSyncedAt: Date | null;
  id: Generated<string>;
  itemStyleNo: string | null;
  notes: string | null;
  poNumber: string;
  poNumberNorm: string | null;
  quantityUnit: string | null;
  raw: string | null;
  totalQuantity: number | null;
  updatedAt: Generated<Date>;
  vendorId: string | null;
}

export interface RefreshTokens {
  createdAt: Generated<Date>;
  expiresAt: Date;
  id: Generated<string>;
  revokedAt: Date | null;
  tokenHash: string;
  userId: string;
}

export interface ReviewEmail {
  bodyText: string | null;
  createdAt: Generated<Date>;
  emailType: string | null;
  extractedData: string | null;
  extractionConfidence: number | null;
  graphMessageId: string | null;
  id: Generated<string>;
  messageId: string | null;
  originalExtractedData: string | null;
  receivedAt: Date | null;
  reviewedAt: Date | null;
  reviewedBy: string | null;
  reviewerNotes: string | null;
  reviewNotes: string | null;
  reviewStatus: Generated<string>;
  sender: string | null;
  shipmentId: string | null;
  subject: string | null;
  suggestedData: string | null;
  updatedAt: Generated<Date>;
}

export interface ShipmentEmails {
  createdAt: Generated<Date>;
  emailType: string | null;
  graphMessageId: string | null;
  id: Generated<string>;
  receivedAt: Date | null;
  shipmentId: string;
}

export interface ShipmentIdentifiers {
  createdAt: Generated<Date>;
  docType: string | null;
  id: Generated<string>;
  isCurrent: Generated<boolean>;
  observedAt: Date | null;
  rank: number | null;
  shipmentId: string;
  sourceEmailId: string | null;
  type: string;
  value: string;
}

export interface ShipmentMatchKeys {
  createdAt: Generated<Date>;
  id: Generated<string>;
  shipmentId: string;
  type: string;
  value: string;
}

export interface ShipmentMilestones {
  createdAt: Generated<Date>;
  emailMessageId: string | null;
  evidenceRecordId: string | null;
  id: Generated<string>;
  milestoneType: string;
  notes: string | null;
  occurredAt: Date;
  senderType: string | null;
  shipmentId: string;
  signal: string | null;
}

export interface ShipmentParties {
  createdAt: Generated<Date>;
  customerCode: string;
  customerId: string | null;
  customerName: string | null;
  docType: string | null;
  id: Generated<string>;
  isCurrent: Generated<boolean>;
  isPrimary: Generated<boolean>;
  observedAt: Date | null;
  rank: number | null;
  role: string;
  shipmentId: string;
  sourceEmailId: string | null;
}

export interface ShipmentPos {
  createdAt: Generated<Date>;
  id: Generated<string>;
  poId: string;
  quantity: number | null;
  quantityUnit: string | null;
  shipmentId: string;
}

export interface Shipments {
  ata: Date | null;
  atd: Date | null;
  bookingId: string;
  bookingNo: string | null;
  cargoReadyDate: Date | null;
  cfsCutoff: Date | null;
  confidence: number | null;
  confirmedByEmail: Generated<boolean>;
  consigneeAddress: string | null;
  consigneeId: string | null;
  consigneeName: string | null;
  containerNo: string | null;
  createdAt: Generated<Date>;
  dismissedAt: Date | null;
  eta: Date | null;
  etd: Date | null;
  flightNo: string | null;
  forwarderId: string | null;
  forwarderRaw: string | null;
  grossWeight: number | null;
  hblAwbFcrNo: string | null;
  htsCode: string | null;
  id: Generated<string>;
  inDcDate: Date | null;
  itemStyleNo: string | null;
  kind: Generated<string>;
  legNo: Generated<number>;
  legStatus: Generated<string>;
  linkedShipmentId: string | null;
  matchKeys: string | null;
  mawb: string | null;
  mbl: string | null;
  measurement: number | null;
  mode: string | null;
  originCountry: string | null;
  podId: string | null;
  podRaw: string | null;
  polId: string | null;
  polRaw: string | null;
  qty: number | null;
  qtyUnit: string | null;
  reviewedAt: Date | null;
  reviewedBy: string | null;
  reviewReasons: string | null;
  reviewStatus: Generated<string>;
  riskLevel: Generated<string>;
  scacCode: string | null;
  soNo: string | null;
  state: Generated<string>;
  supersededById: string | null;
  updatedAt: Generated<Date>;
  vesselName: string | null;
  voyageNo: string | null;
  warehouseEndDate: Date | null;
  warehouseStartDate: Date | null;
}

export interface Users {
  active: Generated<boolean>;
  avatarInitials: string | null;
  createdAt: Generated<Date>;
  email: string;
  id: Generated<string>;
  mustReset: Generated<boolean>;
  name: string;
  passwordHash: string;
  role: Generated<string>;
  updatedAt: Generated<Date>;
}

export interface Vendors {
  code: string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  createdAt: Generated<Date>;
  erpSyncedAt: Date | null;
  id: Generated<string>;
  location: string | null;
  name: string;
  notes: string | null;
  type: Generated<string>;
  updatedAt: Generated<Date>;
}

export interface DB {
  alertRules: AlertRules;
  alerts: Alerts;
  appSettings: AppSettings;
  bookingPos: BookingPos;
  bookings: Bookings;
  carriers: Carriers;
  changeLog: ChangeLog;
  consignees: Consignees;
  customers: Customers;
  emailAttachment: EmailAttachment;
  emailMessage: EmailMessage;
  emailRead: EmailRead;
  fieldLocks: FieldLocks;
  forwarderAliases: ForwarderAliases;
  forwarders: Forwarders;
  ingestState: IngestState;
  masterResolution: MasterResolution;
  parsedRecord: ParsedRecord;
  ports: Ports;
  purchaseOrders: PurchaseOrders;
  refreshTokens: RefreshTokens;
  reviewEmail: ReviewEmail;
  shipmentEmails: ShipmentEmails;
  shipmentIdentifiers: ShipmentIdentifiers;
  shipmentMatchKeys: ShipmentMatchKeys;
  shipmentMilestones: ShipmentMilestones;
  shipmentParties: ShipmentParties;
  shipmentPos: ShipmentPos;
  shipments: Shipments;
  users: Users;
  vendors: Vendors;
}
